name: CI

on:
  pull_request:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Run tests
        run: |
          npm run test
          npm run test-readme
          npm run test-docs
          npm run test-browser
